/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CertificateNFT {
  export type CertificateDataStruct = {
    courseTitle: string;
    learnerName: string;
    score: BigNumberish;
    completionTimestamp: BigNumberish;
    metadataURI: string;
  };

  export type CertificateDataStructOutput = [
    courseTitle: string,
    learnerName: string,
    score: bigint,
    completionTimestamp: bigint,
    metadataURI: string
  ] & {
    courseTitle: string;
    learnerName: string;
    score: bigint;
    completionTimestamp: bigint;
    metadataURI: string;
  };
}

export interface CertificateNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "certificates"
      | "getCertificate"
      | "getLearnerCertificates"
      | "learnerCertificates"
      | "mintCertificate"
      | "name"
      | "nextTokenId"
      | "ownerOf"
      | "symbol"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateMinted"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLearnerCertificates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "learnerCertificates",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCertificate",
    values: [AddressLike, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLearnerCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "learnerCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export namespace CertificateMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    learner: AddressLike,
    courseTitle: string,
    score: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    learner: string,
    courseTitle: string,
    score: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    learner: string;
    courseTitle: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateNFT extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateNFT;
  waitForDeployment(): Promise<this>;

  interface: CertificateNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  certificates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        courseTitle: string;
        learnerName: string;
        score: bigint;
        completionTimestamp: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [tokenId: BigNumberish],
    [CertificateNFT.CertificateDataStructOutput],
    "view"
  >;

  getLearnerCertificates: TypedContractMethod<
    [learner: AddressLike],
    [bigint[]],
    "view"
  >;

  learnerCertificates: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  mintCertificate: TypedContractMethod<
    [
      learner: AddressLike,
      courseTitle: string,
      learnerName: string,
      score: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  ownerOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        courseTitle: string;
        learnerName: string;
        score: bigint;
        completionTimestamp: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [CertificateNFT.CertificateDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLearnerCertificates"
  ): TypedContractMethod<[learner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "learnerCertificates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCertificate"
  ): TypedContractMethod<
    [
      learner: AddressLike,
      courseTitle: string,
      learnerName: string,
      score: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  getEvent(
    key: "CertificateMinted"
  ): TypedContractEvent<
    CertificateMintedEvent.InputTuple,
    CertificateMintedEvent.OutputTuple,
    CertificateMintedEvent.OutputObject
  >;

  filters: {
    "CertificateMinted(uint256,address,string,uint256)": TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;
    CertificateMinted: TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;
  };
}
