/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CourseRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "approveCourse"
      | "courseIds"
      | "courses"
      | "enrollInCourse"
      | "getCourseCount"
      | "isEnrolled"
      | "registerCourse"
      | "submitForApproval"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CourseEnrolled"
      | "CourseRegistered"
      | "CourseStatusChanged"
      | "ProviderPayout"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "courseIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "courses", values: [string]): string;
  encodeFunctionData(
    functionFragment: "enrollInCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourseCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isEnrolled",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCourse",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitForApproval",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courseIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enrollInCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCourseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEnrolled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitForApproval",
    data: BytesLike
  ): Result;
}

export namespace CourseEnrolledEvent {
  export type InputTuple = [
    courseId: string,
    learner: AddressLike,
    feePaid: BigNumberish
  ];
  export type OutputTuple = [
    courseId: string,
    learner: string,
    feePaid: bigint
  ];
  export interface OutputObject {
    courseId: string;
    learner: string;
    feePaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseRegisteredEvent {
  export type InputTuple = [
    courseId: string,
    title: string,
    provider: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    courseId: string,
    title: string,
    provider: string,
    price: bigint
  ];
  export interface OutputObject {
    courseId: string;
    title: string;
    provider: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseStatusChangedEvent {
  export type InputTuple = [courseId: string, status: BigNumberish];
  export type OutputTuple = [courseId: string, status: bigint];
  export interface OutputObject {
    courseId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderPayoutEvent {
  export type InputTuple = [provider: AddressLike, amount: BigNumberish];
  export type OutputTuple = [provider: string, amount: bigint];
  export interface OutputObject {
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CourseRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CourseRegistry;
  waitForDeployment(): Promise<this>;

  interface: CourseRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  approveCourse: TypedContractMethod<[courseId: string], [void], "nonpayable">;

  courseIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  courses: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, bigint, bigint] & {
        courseId: string;
        title: string;
        provider: string;
        price: bigint;
        rewardPool: bigint;
        status: bigint;
        totalEnrollments: bigint;
        totalRevenue: bigint;
      }
    ],
    "view"
  >;

  enrollInCourse: TypedContractMethod<[courseId: string], [void], "payable">;

  getCourseCount: TypedContractMethod<[], [bigint], "view">;

  isEnrolled: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  registerCourse: TypedContractMethod<
    [
      courseId: string,
      title: string,
      price: BigNumberish,
      rewardPool: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitForApproval: TypedContractMethod<
    [courseId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveCourse"
  ): TypedContractMethod<[courseId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "courseIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, bigint, bigint] & {
        courseId: string;
        title: string;
        provider: string;
        price: bigint;
        rewardPool: bigint;
        status: bigint;
        totalEnrollments: bigint;
        totalRevenue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "enrollInCourse"
  ): TypedContractMethod<[courseId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "getCourseCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEnrolled"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerCourse"
  ): TypedContractMethod<
    [
      courseId: string,
      title: string,
      price: BigNumberish,
      rewardPool: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitForApproval"
  ): TypedContractMethod<[courseId: string], [void], "nonpayable">;

  getEvent(
    key: "CourseEnrolled"
  ): TypedContractEvent<
    CourseEnrolledEvent.InputTuple,
    CourseEnrolledEvent.OutputTuple,
    CourseEnrolledEvent.OutputObject
  >;
  getEvent(
    key: "CourseRegistered"
  ): TypedContractEvent<
    CourseRegisteredEvent.InputTuple,
    CourseRegisteredEvent.OutputTuple,
    CourseRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CourseStatusChanged"
  ): TypedContractEvent<
    CourseStatusChangedEvent.InputTuple,
    CourseStatusChangedEvent.OutputTuple,
    CourseStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderPayout"
  ): TypedContractEvent<
    ProviderPayoutEvent.InputTuple,
    ProviderPayoutEvent.OutputTuple,
    ProviderPayoutEvent.OutputObject
  >;

  filters: {
    "CourseEnrolled(string,address,uint256)": TypedContractEvent<
      CourseEnrolledEvent.InputTuple,
      CourseEnrolledEvent.OutputTuple,
      CourseEnrolledEvent.OutputObject
    >;
    CourseEnrolled: TypedContractEvent<
      CourseEnrolledEvent.InputTuple,
      CourseEnrolledEvent.OutputTuple,
      CourseEnrolledEvent.OutputObject
    >;

    "CourseRegistered(string,string,address,uint256)": TypedContractEvent<
      CourseRegisteredEvent.InputTuple,
      CourseRegisteredEvent.OutputTuple,
      CourseRegisteredEvent.OutputObject
    >;
    CourseRegistered: TypedContractEvent<
      CourseRegisteredEvent.InputTuple,
      CourseRegisteredEvent.OutputTuple,
      CourseRegisteredEvent.OutputObject
    >;

    "CourseStatusChanged(string,uint8)": TypedContractEvent<
      CourseStatusChangedEvent.InputTuple,
      CourseStatusChangedEvent.OutputTuple,
      CourseStatusChangedEvent.OutputObject
    >;
    CourseStatusChanged: TypedContractEvent<
      CourseStatusChangedEvent.InputTuple,
      CourseStatusChangedEvent.OutputTuple,
      CourseStatusChangedEvent.OutputObject
    >;

    "ProviderPayout(address,uint256)": TypedContractEvent<
      ProviderPayoutEvent.InputTuple,
      ProviderPayoutEvent.OutputTuple,
      ProviderPayoutEvent.OutputObject
    >;
    ProviderPayout: TypedContractEvent<
      ProviderPayoutEvent.InputTuple,
      ProviderPayoutEvent.OutputTuple,
      ProviderPayoutEvent.OutputObject
    >;
  };
}
