import { Award, BookOpen, CheckCircle2, Sparkles } from "lucide-react";
import { getStudentData } from "@/lib/student-data";

export default async function PortfolioPage() {
  const { progress, certificates, nfts, errors } = await getStudentData();
  const completed = progress.filter((item) => Number(item.percentage) >= 100).length;
  return <main className="mx-auto max-w-6xl px-4 py-8 lg:px-8">
    <header className="mb-8"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#0056D2]">Own</p><h1 className="mt-2 text-3xl font-black text-slate-900">Learning Portfolio</h1><p className="mt-2 text-sm text-slate-500">Your verified learning progress and credentials in one place.</p></header>
    {errors.length > 0 && <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Some portfolio records are unavailable from the current database connection.</div>}
    <section className="grid gap-4 sm:grid-cols-3"><Stat label="Courses tracked" value={progress.length} icon={BookOpen} /><Stat label="Completed" value={completed} icon={CheckCircle2} /><Stat label="Credentials" value={certificates.length + nfts.length} icon={Award} /></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Course progress" icon={BookOpen}>{progress.length ? progress.map((item) => <div key={String(item.id)} className="mb-3 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-sm font-semibold text-slate-800"><span>Course {item.course_id}</span><span>{item.percentage}%</span></div><div className="mt-3 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-[#0056D2]" style={{ width: `${Math.min(100, Math.max(0, Number(item.percentage)))}%` }} /></div></div>) : <Empty text="Your course progress will appear here after you enroll." />}</Panel><Panel title="Credentials and NFTs" icon={Sparkles}>{certificates.length || nfts.length ? <div className="space-y-3">{[...certificates.map((item) => ({ id: item.id, title: "Certificate", detail: `Course ${item.course_id}` })), ...nfts.map((item) => ({ id: item.token_id, title: item.type || "NFT", detail: item.token_id }))].map((item) => <div key={String(item.id)} className="flex items-center gap-3 rounded-xl bg-slate-50 p-4"><Award className="h-5 w-5 text-amber-500" /><div><p className="font-semibold text-slate-900">{item.title}</p><p className="text-xs text-slate-500">{item.detail}</p></div></div>)}</div> : <Empty text="No credentials have been issued yet." />}</Panel></section>
  </main>;
}
function Stat({ label, value, icon: Icon }: { label: string; value: number; icon: typeof BookOpen }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-[#0056D2]" /><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p></article>; }
function Panel({ title, icon: Icon, children }: { title: string; icon: typeof BookOpen; children: React.ReactNode }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Icon className="h-5 w-5 text-[#0056D2]" /><h2 className="font-bold text-slate-900">{title}</h2></div>{children}</article>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">{text}</div>; }
